"""New Iniatial with all tables

Revision ID: 6a0cd8cdfcc2
Revises: 
Create Date: 2022-10-18 12:48:09.956880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0cd8cdfcc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_email'), 'access', ['email'], unique=True)
    op.create_index(op.f('ix_access_username'), 'access', ['username'], unique=True)
    op.create_table('displaypix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('post', sa.String(length=50), nullable=False),
    sa.Column('elected_date', sa.Date(), nullable=True),
    sa.Column('where', sa.String(length=5), nullable=False),
    sa.Column('alias', sa.String(length=10), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executives_elected_date'), 'executives', ['elected_date'], unique=False)
    op.create_table('gallery_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('other_names', sa.String(length=75), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone2', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('initiation_date', sa.Date(), nullable=True),
    sa.Column('investiture_date', sa.Date(), nullable=True),
    sa.Column('place_initiated', sa.String(length=150), nullable=True),
    sa.Column('initiated_sc', sa.String(length=150), nullable=True),
    sa.Column('current_sc', sa.String(length=150), nullable=True),
    sa.Column('degree', sa.String(length=10), nullable=True),
    sa.Column('ksmno', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('state_of_origin', sa.String(length=20), nullable=True),
    sa.Column('home_town', sa.String(length=120), nullable=True),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('work_title', sa.String(length=100), nullable=True),
    sa.Column('work_place', sa.String(length=150), nullable=True),
    sa.Column('work_address', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_birth_date'), 'members', ['birth_date'], unique=False)
    op.create_index(op.f('ix_members_initiation_date'), 'members', ['initiation_date'], unique=False)
    op.create_index(op.f('ix_members_investiture_date'), 'members', ['investiture_date'], unique=False)
    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(length=120), nullable=True),
    sa.Column('alias', sa.String(length=20), nullable=True),
    sa.Column('arm', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pastexecutives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('post', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('where', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pastexecutives_end_date'), 'pastexecutives', ['end_date'], unique=False)
    op.create_index(op.f('ix_pastexecutives_start_date'), 'pastexecutives', ['start_date'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('other_names', sa.String(length=75), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phone1', sa.String(length=20), nullable=True),
    sa.Column('phone2', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('work_place', sa.String(length=150), nullable=True),
    sa.Column('work_address', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('posted_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['posted_by'], ['access.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_date_created'), 'news', ['date_created'], unique=False)
    op.create_table('photo_gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('caption', sa.String(length=120), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('display_type', sa.Integer(), nullable=False),
    sa.Column('gallery_options', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['display_type'], ['displaypix.id'], ),
    sa.ForeignKeyConstraint(['gallery_options'], ['gallery_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_gallery')
    op.drop_index(op.f('ix_news_date_created'), table_name='news')
    op.drop_table('news')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_pastexecutives_start_date'), table_name='pastexecutives')
    op.drop_index(op.f('ix_pastexecutives_end_date'), table_name='pastexecutives')
    op.drop_table('pastexecutives')
    op.drop_table('offices')
    op.drop_index(op.f('ix_members_investiture_date'), table_name='members')
    op.drop_index(op.f('ix_members_initiation_date'), table_name='members')
    op.drop_index(op.f('ix_members_birth_date'), table_name='members')
    op.drop_table('members')
    op.drop_table('gallery_options')
    op.drop_index(op.f('ix_executives_elected_date'), table_name='executives')
    op.drop_table('executives')
    op.drop_table('displaypix')
    op.drop_index(op.f('ix_access_username'), table_name='access')
    op.drop_index(op.f('ix_access_email'), table_name='access')
    op.drop_table('access')
    # ### end Alembic commands ###
