"""Access and other tables

Revision ID: a60b0a9abaac
Revises: 
Create Date: 2019-02-22 23:24:00.846334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60b0a9abaac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_email'), 'access', ['email'], unique=True)
    op.create_index(op.f('ix_access_username'), 'access', ['username'], unique=True)
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('other_names', sa.String(length=75), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('initiation_date', sa.Date(), nullable=True),
    sa.Column('investiture_date', sa.Date(), nullable=True),
    sa.Column('home_town', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_birth_date'), 'membership', ['birth_date'], unique=False)
    op.create_index(op.f('ix_membership_initiation_date'), 'membership', ['initiation_date'], unique=False)
    op.create_index(op.f('ix_membership_investiture_date'), 'membership', ['investiture_date'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('other_names', sa.String(length=75), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone1', sa.String(length=20), nullable=False),
    sa.Column('phone2', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('work_place', sa.String(length=150), nullable=True),
    sa.Column('work_address', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_index(op.f('ix_membership_investiture_date'), table_name='membership')
    op.drop_index(op.f('ix_membership_initiation_date'), table_name='membership')
    op.drop_index(op.f('ix_membership_birth_date'), table_name='membership')
    op.drop_table('membership')
    op.drop_index(op.f('ix_access_username'), table_name='access')
    op.drop_index(op.f('ix_access_email'), table_name='access')
    op.drop_table('access')
    # ### end Alembic commands ###
