"""update members table

Revision ID: cbac6d18202d
Revises: deb753bdb2ec
Create Date: 2020-03-19 13:48:09.814029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbac6d18202d'
down_revision = 'deb753bdb2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('current_sc', sa.String(length=150), nullable=True))
    op.add_column('members', sa.Column('degree', sa.String(length=10), nullable=True))
    op.add_column('members', sa.Column('initiated_sc', sa.String(length=150), nullable=True))
    op.add_column('members', sa.Column('ksmno', sa.String(length=10), nullable=True))
    op.add_column('members', sa.Column('nationality', sa.String(length=100), nullable=True))
    op.add_column('members', sa.Column('place_initiated', sa.String(length=150), nullable=True))
    op.add_column('members', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'status')
    op.drop_column('members', 'place_initiated')
    op.drop_column('members', 'nationality')
    op.drop_column('members', 'ksmno')
    op.drop_column('members', 'initiated_sc')
    op.drop_column('members', 'degree')
    op.drop_column('members', 'current_sc')
    # ### end Alembic commands ###
