"""created gallery option table

Revision ID: 37bbe1755ba8
Revises: 631fce4363d4
Create Date: 2019-03-20 14:12:32.658699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37bbe1755ba8'
down_revision = '631fce4363d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('photo_gallery', sa.Column('gallery_options', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photo_gallery', 'gallery_options', ['gallery_options'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo_gallery', type_='foreignkey')
    op.drop_column('photo_gallery', 'gallery_options')
    op.drop_table('gallery_options')
    # ### end Alembic commands ###
