"""created tables DisplayPix(setup tabs for pix) and renamed Carousel to PhotoGalley to handle anything pix

Revision ID: 631fce4363d4
Revises: f793be19f662
Create Date: 2019-03-13 15:47:01.982932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631fce4363d4'
down_revision = 'f793be19f662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('displaypix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('caption', sa.String(length=120), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('display_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['display_type'], ['displaypix.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('carousel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carousel',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('caption', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='carousel_pkey')
    )
    op.drop_table('photo_gallery')
    op.drop_table('displaypix')
    # ### end Alembic commands ###
