"""updated member and access tables

Revision ID: deb753bdb2ec
Revises: e028501164e3
Create Date: 2020-03-06 07:09:28.592246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb753bdb2ec'
down_revision = 'e028501164e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('other_names', sa.String(length=75), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone2', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('initiation_date', sa.Date(), nullable=True),
    sa.Column('investiture_date', sa.Date(), nullable=True),
    sa.Column('state_of_origin', sa.String(length=20), nullable=True),
    sa.Column('home_town', sa.String(length=120), nullable=True),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('work_title', sa.String(length=100), nullable=True),
    sa.Column('work_place', sa.String(length=150), nullable=True),
    sa.Column('work_address', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_birth_date'), 'members', ['birth_date'], unique=False)
    op.create_index(op.f('ix_members_initiation_date'), 'members', ['initiation_date'], unique=False)
    op.create_index(op.f('ix_members_investiture_date'), 'members', ['investiture_date'], unique=False)
    op.drop_index('ix_memberships_birth_date', table_name='memberships')
    op.drop_index('ix_memberships_initiation_date', table_name='memberships')
    op.drop_index('ix_memberships_investiture_date', table_name='memberships')
    op.drop_table('memberships')
    op.add_column('access', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access', 'is_admin')
    op.create_table('memberships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('other_names', sa.VARCHAR(length=75), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('initiation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('investiture_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('home_town', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('access_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state_of_origin', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('phone2', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('work_address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('work_place', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('work_title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['access_id'], ['access.id'], name='memberships_access_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='memberships_pkey')
    )
    op.create_index('ix_memberships_investiture_date', 'memberships', ['investiture_date'], unique=False)
    op.create_index('ix_memberships_initiation_date', 'memberships', ['initiation_date'], unique=False)
    op.create_index('ix_memberships_birth_date', 'memberships', ['birth_date'], unique=False)
    op.drop_index(op.f('ix_members_investiture_date'), table_name='members')
    op.drop_index(op.f('ix_members_initiation_date'), table_name='members')
    op.drop_index(op.f('ix_members_birth_date'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
