"""updated profiles table

Revision ID: e028501164e3
Revises: 4734ccd5c004
Create Date: 2020-03-06 00:08:29.426509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e028501164e3'
down_revision = '4734ccd5c004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'address',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('profiles', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('profiles', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('profiles', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('profiles', 'phone1',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'phone1',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('profiles', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('profiles', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('profiles', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('profiles', 'address',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
