"""added phone to membership table

Revision ID: f793be19f662
Revises: e1b1068e884f
Create Date: 2019-03-09 12:46:24.625606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f793be19f662'
down_revision = 'e1b1068e884f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'phone')
    # ### end Alembic commands ###
